package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"strconv"
	"strings"

	"github.com/Shelnutt2/db2struct"
	goopt "github.com/droundy/goopt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/howeyc/gopass"
)

var mariadbHost = os.Getenv("MYSQL_HOST")
var mariadbHostPassed = goopt.String([]string{"-H", "--host"}, "localhost", "Host to check mariadb status of")
var mariadbPort = goopt.Int([]string{"--mysql_port"}, 3306, "Specify a port to connect to")
var mariadbTable = goopt.String([]string{"-t", "--table"}, "", "Table to build struct from")
var mariadbDatabase = goopt.String([]string{"-d", "--database"}, "nil", "Database to for connection")
var mariadbPassword *string
var mariadbUser = goopt.String([]string{"-u", "--user"}, "root", "user to connect to database")
var verbose = goopt.Flag([]string{"-v", "--verbose"}, []string{}, "Enable verbose output", "")
var packageName = goopt.String([]string{"--package"}, "", "name to set for package")
var structName = goopt.String([]string{"--struct"}, "", "name to set for struct")

var jsonAnnotation = goopt.Flag([]string{"--json"}, []string{"--no-json"}, "Add json annotations (default)", "Disable json annotations")
var gormAnnotation = goopt.Flag([]string{"--gorm"}, []string{}, "Add gorm annotations (tags)", "")
var gureguTypes = goopt.Flag([]string{"--guregu"}, []string{}, "Add guregu null types", "")

func init() {
	goopt.OptArg([]string{"-p", "--password"}, "", "Mysql password", getMariadbPassword)
	//goopt.ReqArg([]string{"-u", "--user"}, "user", "user to connect to database", setUser)

	// Setup goopts
	goopt.Description = func() string {
		return "Mariadb http Check"
	}
	goopt.Version = "0.0.2"
	goopt.Summary = "db2struct [-H] [-p] [-v] --package pkgName --struct structName --database databaseName --table tableName"

	//Parse options
	goopt.Parse(nil)

}

func main() {

	// Username is required
	if mariadbUser == nil || *mariadbUser == "user" {
		fmt.Println("Username is required! Add it with --user=name")
		return
	}

	// If a mariadb host is passed use it
	if mariadbHostPassed != nil && *mariadbHostPassed != "" {
		mariadbHost = *mariadbHostPassed
	}

	if mariadbPassword != nil && *mariadbPassword == "" {
		fmt.Print("Password: ")
		pass, err := gopass.GetPasswd()
		stringPass := string(pass)
		mariadbPassword = &stringPass
		if err != nil {
			fmt.Println("Error reading password: " + err.Error())
			return
		}
	}

	if *verbose {
		fmt.Println("Connecting to mysql server " + mariadbHost + ":" + strconv.Itoa(*mariadbPort))
	}

	if mariadbDatabase == nil || *mariadbDatabase == "" {
		fmt.Println("Database can not be null")
		return
	}

	// If structName is not set we need to default it
	if structName == nil || *structName == "" {
		*structName = "newstruct"
	}
	// If packageName is not set we need to default it
	if packageName == nil || *packageName == "" {
		*packageName = "newpackage"
	}

	var tables []string
	var err error
	if mariadbTable == nil || *mariadbTable == "" {
		tables, err = db2struct.GetTables(*mariadbUser, *mariadbPassword, mariadbHost, *mariadbPort, *mariadbDatabase)
		if err != nil {
			fmt.Println("GetTables: " + err.Error())
			return
		}
	} else {
		tables = []string{*mariadbTable}
	}

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// Generated by tool, don't add other logic.\n\npackage %s\n\n", *packageName))
	for _, tbl := range tables {
		str, err := export(tbl, parseStructName(tbl))
		if err != nil {
			return
		}
		buf.Write(str)
	}
	// fmt.Println(buf.String())
	fn := *packageName + ".go"
	ioutil.WriteFile(fn, buf.Bytes(), 0644)
	fmt.Println("exported to", fn)
}

func getMariadbPassword(password string) error {
	mariadbPassword = new(string)
	*mariadbPassword = password
	return nil
}

func export(tableName, structName string) ([]byte, error) {
	columnDataTypes, err := db2struct.GetColumnsFromMysqlTable(*mariadbUser, *mariadbPassword, mariadbHost, *mariadbPort, *mariadbDatabase, tableName)
	if err != nil {
		fmt.Println("Error in selecting column data information from mysql information schema")
		return nil, err
	}

	// Generate struct string based on columnDataTypes
	struc, err := db2struct.Generate(*columnDataTypes, tableName, structName, *packageName, *jsonAnnotation, *gormAnnotation, *gureguTypes)
	if err != nil {
		fmt.Println("Error in creating struct from json: " + err.Error())
		return nil, err
	}

	return struc, nil
}

func parseStructName(name string) string {
	first := name[:1]
	name = strings.ToUpper(first) + name[1:]
	for {
		idx := strings.Index(name, "_")
		if idx == -1 {
			return name
		}
		tag := string(name[idx+1])
		name = name[:idx] + strings.ToUpper(tag) + name[idx+2:]
	}
}
